Flexbox portfolio page
OnlyUnknown/portfolio-mobile-first pull request #1
Opened 2023-01-11 20:16 UTC by OnlyUnknown

Built a Portfolio page with flexbox css property

2023-01-11 21:14 UTC, zieeco requested changes
Hi @OnlyUnknown ,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A


**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 21:14 UTC, zieeco commented on The-page.html
> +            </div>
- Hey to enforce the use of the html5 semantic tag, kindly use the nav tag to wrap this content as this contains the introductory content of your page.

2023-01-11 21:14 UTC, zieeco commented on The-page.html
> +    </div>
- Hey, this part of your webpage should be wrapped in a section tag as this is the first section of your page thereby it should denote that its a section.

2023-01-11 21:14 UTC, zieeco commented on The-page.html
> +    </div>
- Hey, this section contains a list of your social media platform where people can connect with you. it should be wrapped in a ul with it list of items and the link to each social media icon. kindly update this instead of adding all as an image.

2023-01-11 21:14 UTC, zieeco commented on The-page.html
> +    </div>
#### The-page.htm to `index.html`

- Please, kindly rename to index.html as this is the correct way of adding the index.html file in your page because some browsers might not interpret the way you've named it.

2023-01-11 21:14 UTC, zieeco commented on The-page.html
> +    </div>
### .gitignore.txt

- Please, kindly remove this file as you've correctly added the .gitignore file above.

2023-01-11 21:14 UTC, zieeco commented on Style.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
### USE FLEXBOX FOR THE PAGE LAYOUT

- Hey, please, kindly use flexbox to control your page layout as this helps your design be responsive. Your current design won't be flexible on all devices. please, kindly improve the styles to make your design have a better feel.

2023-01-11 21:14 UTC, zieeco commented on Style.css
> +  background-size: cover;
- Hey, your background image is not well aligned according to the design template. please, kindly improve on this below:

- Kindly align the content on the page correctly. pay a close attention to the padding, margins, etc.
- Use the correct color for the paragraph
- Use the Correct font size and font-weight


*your design*
![Screenshot from 2023-01-11 21-52-54](https://user-images.githubusercontent.com/59397159/211915445-f2e7db07-bb2a-4609-9452-da08758fb5a1.png)

*design template*
![Screenshot from 2023-01-11 21-52-23](https://user-images.githubusercontent.com/59397159/211915454-02b4f849-964a-4704-bda4-6758d6771bea.png)

2023-01-11 21:14 UTC, zieeco commented on README.md
> +
### GENERAL REVIEW FOR THE README FILE


- Hey, Please, kindly remove all placeholder text in the readme file. These placeholder texts are there to guide you on how to add the necessary content, so they're not expected to be in the readme after you customize it to suit your project needs. e.g 
> Describe 1 - 3 features you will add to the project.
---

- Please, kindly update this section in the image below, remove the headers that are not relevant to the project e.g (test), add some instructions on how users can have your project run locally on their machine, 

:point_down: 
![Screenshot from 2023-01-11 22-02-45](https://user-images.githubusercontent.com/59397159/211917195-0cd00c3d-863b-430c-84c2-ddb64186418d.png)
---
- Kindly tell users some features of the project so they can have an idea what the project is all about.
- Kindly add a license with a working link as this currently is broken to improve your readme file.
- kindly add some acknowledgment and some questions and answers about the project below:

:point_down: 
![Screenshot from 2023-01-11 22-08-22](https://user-images.githubusercontent.com/59397159/211918238-d26a689d-a90d-4be4-9e18-90bab3b69b20.png)

2023-01-12 10:30 UTC, emmiiorji requested changes
Hi @OnlyUnknown, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Proper use of GitHub flow


 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 10:30 UTC, emmiiorji commented on Style.css
> +}
As suggested by the previous reviewer and as [required](https://github.com/microverseinc/curriculum-html-css/blob/096130a7c3e71e15c3c97ddc2ed0ec6467621a8c/portfolio/1_setup.md?plain=1#L58) for this project, kindly ensure that the headline section is laid out using flexbox.

2023-01-12 10:30 UTC, emmiiorji commented on Style.css
> +  background-size: cover;
As the previous reviewer suggested, kindly adjust the design of the headline section to match the figma template.

Modify the background image to as to be centred on the page. Also adjust margins as shown in the illustration below:

Your design:
![image](https://user-images.githubusercontent.com/20554583/212042875-deb9133b-239e-41e4-b048-74b6c6e338c5.png)



Figma design:
![image](https://user-images.githubusercontent.com/20554583/212043324-e1603f09-05fd-4295-b966-492fa0e3cb87.png)

2023-01-12 14:56 UTC, MeqdamAlqudah requested changes
Hi @OnlyUnknown , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![image](https://user-images.githubusercontent.com/74744787/212099909-e48014ac-2112-4035-bc3e-273ccc89c42d.png)

 ## Highlights
:+1: Readme file
:+1: No Linter errors

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 14:56 UTC, MeqdamAlqudah commented on Style.css
> +  font-size: 20px;
- [ ] Please as suggested by the previous reviewer and as [required](https://github.com/microverseinc/curriculum-html-css/blob/096130a7c3e71e15c3c97ddc2ed0ec6467621a8c/portfolio/1_setup.md?plain=1#L58) for this project, kindly ensure that the headline section is laid out using flexbox.

2023-01-12 14:56 UTC, MeqdamAlqudah commented on Style.css
> +  font-style: normal;
-  [ ] As the previous reviewer suggested, kindly adjust the design of the headline section to match the Figma template for the margin, title color, and background position please fix them.

| Your code  | Figma |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/74744787/212096209-452f07a8-a050-42c6-89bb-3ea6fa5aafdb.png)  | ![image](https://user-images.githubusercontent.com/74744787/212096525-fbb441bc-af66-40bc-90e8-23e4caf03def.png)  |

- [ Optional ] Please fix the margin between the headline title and the toolbar 
![image](https://user-images.githubusercontent.com/74744787/212097023-048b6815-0527-4d15-b530-b354971d0c1d.png)
 
- [ Optional ] the toolbar section doesn't match the design the logo should be aligned to the left while the hamburger button should be aligned to the right also the background of the toolbar section should match the design.

| Your code  | Figma |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/74744787/212098851-0d2e7b44-1329-4ac7-813a-173575e141e8.png)  | ![image](https://user-images.githubusercontent.com/74744787/212098953-5ef64175-a0f5-4fc1-af44-6d676b663679.png)  |

2023-01-12 16:50 UTC, mukhammadrizooff requested changes
Hi @OnlyUnknown, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 16:50 UTC, mukhammadrizooff commented on Style.css
> +}
- [ ] [REQUIRED] Good job so far! Please follow the requirements of previous code reviewers who asked you to style the header page like [Figma's design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468&t=8eIA2vsE9FRfB1Q2-0). I will try to explain it to you again. The background picture of your project should be fully reflected in the `mobile` version, and the `hx`, and `p` elements should be `positioned` as shown in the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468&t=8eIA2vsE9FRfB1Q2-0), the correct CSS properties should be given, and the `thickness` and `fonts` should also be as shown in the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468&t=8eIA2vsE9FRfB1Q2-0). should be Once again, I ask you to compare your project with the template in [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468&t=8eIA2vsE9FRfB1Q2-0) after completing this request to the end. We gave you tips for that you don't have any difficulties in the upcoming milestones, and we trust you to follow our advice. We wish you good luck 😃 


![image](https://user-images.githubusercontent.com/63915024/212129119-a776b5f4-c8ba-4234-84a7-a017b89888ee.png)

2023-01-12 20:27 UTC, vickymarz requested changes
Hi @OnlyUnknown, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 20:27 UTC, vickymarz commented on index.html
> +        </header>
- [ ] As suggested by the previous reviewer, Kindly align the content of your header properly and also add the styling to match the Figma design template you chose. I will recommend you use flexbox to properly align the contents of the header. read about flexbox [here](https://www.w3schools.com/css/css3_flexbox.asp)

I also noticed a background on the header which is not present on the design. KIndly remove it 👍🏽 

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/212172372-ee76a3cd-a623-4d8c-9185-4cc3221d3ed2.png) | ![image](https://user-images.githubusercontent.com/63473584/212172885-905104dc-82e6-43c9-bb8f-30e1bb899f04.png)  |

2023-01-12 20:27 UTC, vickymarz commented on index.html
> +        </h3>
- [ ] I also noticed you changed the color of the headline text and it also contains a typo in the `software` spelling. Kindly ensure the color matches the Figma design text color 👍🏽 

| Figma Design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/212173753-644c9e40-4f99-4f95-99c8-8985fd6953c6.png)  | ![image](https://user-images.githubusercontent.com/63473584/212173944-9b021a2c-ccb6-4b43-9c90-c12e824ec75d.png)  |

2023-01-13 07:31 UTC, brainconnect93 requested changes
# STATUS: Changes Required :recycle:

### Hi @OnlyUnknown, 👋 

Good job so far, You really made a great effort working on your project, it looks really awesome! but there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 07:31 UTC, brainconnect93 commented on Style.css
> +  flex-grow: 0;
- [ ] As suggested by all the previous reviewers, I notice what they requested you work on is still undone by you. Currently, your project is not aligning very well with the mobile screen size, and the goal of this project is to work on the project in mobile screen size and the ability to replicate the design given to you by a client, with this, any client can be more confident in you to deliver a better job for him.

- [ ] My humble advice is to please work on your project alignment and make sure it fits perfectly to the mobile screen size.

Your design 👇 

![only](https://user-images.githubusercontent.com/78634841/212262304-76624b85-ed8d-488c-98d4-8a5ebcbb50f4.png)

Figma design 👇 

![temp real](https://user-images.githubusercontent.com/78634841/212262666-cd9230c2-614a-448d-a0cb-ae4637d675a4.png)

2023-01-16 10:23 UTC, ha-manel approved these changes
# STATUS: APPROVED ✅

## Hi @OnlyUnknown 👋

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉**

<img src="https://media3.giphy.com/media/l4JySAWfMaY7w88sU/giphy.gif"/>

## Highlights:
* All the required changed have been implemented ✔️ 
* All tests passed ✔️ 

## Optional suggestions:

- [ ] Please consider using best practices when you write commit messages, they should be capitalized sentences in the imperative form, example: "Add linters" instead of "added linters" or "linters are added" ... etc 👍 
- [ ] Kindly consider using a directory for the images and the project assets, the project would look cleaner that way (if you do that, don't forget to change the paths to the images in your code) 💯 
- [ ] Kindly add the MIT file to your project because the link in your README is broken 👍 

_Kindly check the comments below_


------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 11:13 UTC, merged