Mobile menu
OnlyUnknown/portfolio-mobile-first pull request #10
Opened 2023-02-06 20:33 UTC by OnlyUnknown

-Menu icon has been added
-Toggle has been added
-Content inside the menu has been added
-Cross has been added for the toggle menu when it is open.

2023-02-06 20:52 UTC, huseyinbiyik commented
Hi  @OnlyUnknown  & @dev-mamun,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

⚠️  Kindly use customize your README and make sure all the main sections present in yours and placeholders are replaced with your project and personal data. Please remove all the instructions targeting you. For example: "Describe how a new developer could make use of your project." The only optional section is the FAQ. Please remove the template logo on the top, if you have your own logo you can replace it with this one, otherwise please delete it. This is crucial to have a professional and instructive repository. 👌 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-06 21:47 UTC, Whoistolu requested changes
Hi @OnlyUnknown 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._
- [ ] [REQUIRED] I am recommending this here because of the License section is not present on your README file changes. Kindly ensure that this project is properly licensed by fixing the broken MIT link.
<img width="766" alt="Screenshot 2023-02-06 at 22 45 45" src="https://user-images.githubusercontent.com/58692590/217095115-f3fe689a-1c05-4d5e-942e-2cd6ff5073c1.png">


### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-06 21:47 UTC, Whoistolu commented on Actions.js
> +document.getElementById('btn').addEventListener('click', changeIcon());
- [ ] [REQUIRED] You have done a great job so far @OnlyUnknown 👍🏽 . However, you still need to ensure that the mobile page covers the display screen 100%. I am not supposed to see `p` tag with the classNmae 'content' when I click the mobile menu, I am supposed to see only 'Projects', 'About', and 'Contact'. Kindly fix this before asking for another review.

Your Implementation   |  Figma Design
:-------------------------:|:-------------------------:
<img width="300" alt="Screenshot 2023-02-06 at 22 25 25" src="https://user-images.githubusercontent.com/58692590/217094183-5f023316-872f-49d0-b4a9-5480fe0481b1.png"> | <img width="221" alt="Screenshot 2023-02-06 at 22 26 10" src="https://user-images.githubusercontent.com/58692590/217094235-b83f63c6-cc20-48fc-a447-b1d262df272a.png">

2023-02-06 21:47 UTC, Whoistolu commented on Actions.js
> +document.getElementById('btn').addEventListener('click', changeIcon());
@OnlyUnknown I can can see that you put a fixed min-width.
<img width="1438" alt="Screenshot 2023-02-06 at 22 34 42" src="https://user-images.githubusercontent.com/58692590/217094543-e7e28344-95af-426b-9274-90a10e58e705.png">

2023-02-06 22:28 UTC, huseyinbiyik requested changes
Hi team,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)

 ## Highlights
- New linter set up well and checks pass 🟢
- Github flow followed 👌


 ## Required Changes ♻️
- As the previous reviewer requested, please make sure your license link works fine. Currently, it is directing me to 404 page. 
![Screen Recording 2023-02-07 at 1 20 12 AM](https://user-images.githubusercontent.com/25887253/217101114-a0a891a0-5e82-423b-94d1-5e89e3f06b3e.gif)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-06 22:28 UTC, huseyinbiyik commented on index.html
> +            <ul id="nav-links" class="navu-menu">
[OPTIONAL] Good job with the full screen mobile navigation. 👍 But I think it would be better UX if you fixed your mobile nav to the screen height. You can use viewport height to do this. 📱

2023-02-07 08:39 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @Team, 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 09:11 UTC, merged